# auto_grad

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                      [3, 4]]).requires_grad_(True)

In [4]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [5]:
# 그래디언트(gradient)를 자동으로 구함
y.backward()

In [7]:
x.grad

tensor([[2., 4.],
        [6., 8.]])

In [12]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

# Gradient Descent

|target| = (3, 3) <br>
|x| = (3, 3) <br>
L(x) = MSE(target, x) <br>
$\hat x = argmin L(x)$ <br>

★x <- x - learning_rate(1)*``L`(X)``★ <br> 
``L`(X)``  -> loss.backword() -> x.grad

![gd.png](gd.png)

In [13]:
import torch.nn.functional as F

In [14]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [16]:
x = torch.rand_like(target)
x.requires_grad  = True
x

tensor([[0.2140, 0.1768, 0.0149],
        [0.0103, 0.5413, 0.3092],
        [0.8338, 0.4860, 0.4857]], requires_grad=True)

In [17]:
loss = F.mse_loss(x, target)
loss

tensor(0.0690, grad_fn=<MseLossBackward0>)

[learning rate](https://bioinformaticsandme.tistory.com/130)

In [18]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward()
    
    x = x - learning_rate * x.grad
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 4.1748e-02
tensor([[0.1887, 0.1820, 0.0783],
        [0.0969, 0.5321, 0.3738],
        [0.8040, 0.5558, 0.5778]], requires_grad=True)
2-th Loss: 2.5255e-02
tensor([[0.1690, 0.1860, 0.1276],
        [0.1642, 0.5250, 0.4241],
        [0.7809, 0.6100, 0.6494]], requires_grad=True)
3-th Loss: 1.5278e-02
tensor([[0.1536, 0.1891, 0.1659],
        [0.2166, 0.5194, 0.4632],
        [0.7629, 0.6523, 0.7051]], requires_grad=True)
4-th Loss: 9.2420e-03
tensor([[0.1417, 0.1915, 0.1957],
        [0.2574, 0.5151, 0.4936],
        [0.7490, 0.6851, 0.7484]], requires_grad=True)
5-th Loss: 5.5908e-03
tensor([[0.1325, 0.1934, 0.2189],
        [0.2891, 0.5118, 0.5172],
        [0.7381, 0.7106, 0.7821]], requires_grad=True)
6-th Loss: 3.3821e-03
tensor([[0.1252, 0.1949, 0.2369],
        [0.3137, 0.5091, 0.5356],
        [0.7296, 0.7305, 0.8083]], requires_grad=True)
7-th Loss: 2.0460e-03
tensor([[0.1196, 0.1960, 0.2509],
        [0.3329, 0.5071, 0.5499],
        [0.7230, 0.7459, 0.8287]], requi