In [1]:
import torch

In [2]:
x = torch.FloatTensor([[[1, 2]],
                      [[3, 4]]])
x.size()

torch.Size([2, 1, 2])

In [3]:
y = x.expand(*[2, 3, 2])
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [7]:
y = torch.cat([x, x, x], dim = 1)
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [8]:
x = torch.randperm(10)
print(x)
print(x.size())

tensor([5, 9, 8, 4, 3, 7, 0, 6, 1, 2])
torch.Size([10])


In [9]:
x = torch.randperm(3**3).reshape(3, 3, -1)
print(x)
print(x.size())

tensor([[[ 1,  9, 17],
         [ 3, 18,  5],
         [ 8,  7,  2]],

        [[25,  0,  6],
         [26, 20,  4],
         [10, 16, 15]],

        [[13, 21, 14],
         [12, 24, 11],
         [19, 22, 23]]])
torch.Size([3, 3, 3])


In [10]:
y = x.argmax(dim = -1)
print(y)
print(y.size())

tensor([[2, 1, 0],
        [0, 0, 1],
        [1, 1, 2]])
torch.Size([3, 3])


In [11]:
values, indices = torch.topk(x, k = 1, dim = -1)
print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [12]:
values.squeeze(-1)

tensor([[17, 18,  8],
        [25, 26, 16],
        [21, 24, 23]])

In [13]:
indices.squeeze(-1)

tensor([[2, 1, 0],
        [0, 0, 1],
        [1, 1, 2]])

In [14]:
x.argmax(dim=-1) == indices.squeeze(-1)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
_, indices = torch.topk(x, k = 2, dim = -1)
indices.size()


torch.Size([3, 3, 2])

In [16]:
x.argmax(dim = -1) == indices[:,:,0]

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [18]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)
print(values)

tensor([[[17,  9,  1],
         [18,  5,  3],
         [ 8,  7,  2]],

        [[25,  6,  0],
         [26, 20,  4],
         [16, 15, 10]],

        [[21, 14, 13],
         [24, 12, 11],
         [23, 22, 19]]])


In [21]:
k = 1 
values, indices = torch.sort(x, dim = -1, descending = True)
values, indices = values[:,:,k], indices[:,:,k]
print(values.squeeze(-1))
print(values.squeeze(-1))

tensor([[ 9,  5,  7],
        [ 6, 20, 15],
        [14, 12, 22]])
tensor([[ 9,  5,  7],
        [ 6, 20, 15],
        [14, 12, 22]])


In [22]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)
print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [23]:
mask = x > 4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [26]:
y = x.masked_fill(mask, value = -1)
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [27]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])
x.size()

torch.Size([2, 3])

In [29]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
